repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_docs
        args:
            - --args=--config=.terraform-docs.yml
        # Only run terraform_docs on .tf files inside 'backplane' or 'buildingblock' folders
        files: ^modules/[^/]+/[^/]+/(backplane|buildingblock)/.+\.tf$
      - id: terraform_fmt
      - id: terragrunt_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: "^compliance/"
